### PR TITLE
Update UG for v1.3 - Add and Edit command

### PR DESCRIPTION
**Pull request by DennieDan**
I have not added the `Income Command`.
Do you all think enhancements like **case-insensitive command words**, **case-insensitive name**, **how duplicates are detected** and **schedule clashing** are worth mentioning?

### CODE REVIEW

**Review by Feng1231 — COMMENTED** [review]
Nice!

**Comment by Feng1231** [comment]
> I have not added the `Income Command`. Do you all think enhancements like **case-insensitive command words**, **case-insensitive name**, **how duplicates are detected** and **schedule clashing** are worth mentioning?

Hmm, I think its good to include reminders to users on duplicates and schedule clashing. Case insensitive features is not necessary imo. What do the others think?

**Comment by teamotitan** [comment]
> I have not added the `Income Command`. Do you all think enhancements like **case-insensitive command words**, **case-insensitive name**, **how duplicates are detected** and **schedule clashing** are worth mentioning?

I think that case-insensitive command words and name can be briefly mentioned. With regards to duplicate detection and schedule clashing, I think talking abit about how it works sounds good, so users know under what scenarios will they encounter these clashes. What do the rest think?

**Comment by DennieDan** [comment]
[like]  Dinh Duy Linh Dan reacted to your message:
________________________________

**Review by Feng1231 — APPROVED** [review]
lgtm!

**Pull request merged**
