### PR TITLE
Fix bug: Valid phone number rejected

### LINKED ISSUE #330: [PE-D][Tester D] Add Command does not accept phone number starting with 3
When inputting add command `add n/John Doe p/31234567 e/johnd@example.com a/John street, block 123, #01-01 t/Tuesday-1300-1500 s/Math r/50.00 paid/100.00 owed/0.00`, error is thrown.

While it satisfies constraints, I am inferring that the team is only accepting Singaporean numbers. In this case, may I suggest for the team to consider allowing 8-digit phone numbers starting with `3` as they are considered valid phone numbers in Singapore, and some older home numbers start with `3`.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: fymbc/ped#3

### PR DESCRIPTION
**Pull request by TY1Fan**
closes #330 

image

Past PR: 
* This [PR](https://github.com/AY2425S1-CS2103T-F14a-1/tp/pull/80) is responsible for the phone number constraint. This PR missed out on the valid output where the phone number starts with 3.

Reason for change:
* Currently phone numbers starting with 3 are not allowed even though phone numbers starting with 3 are valid Singapore phone numbers.

Changes made include:
* updating regex to allow phone numbers starting with 3 
* error message
* user guide

Changes clarified and approved. Refer to this [issue](https://github.com/nus-cs2103-AY2425S1/forum/issues/676).

### CODE REVIEW

**Review by Feng1231 — CHANGES_REQUESTED** [review]
Could we add in the reason for why only 8 digit and 3,6,8,9 is accepted? Or are you going to resolve this in another commit.
Also, It would be good to have a few test case to test this.

You need to cite what is not working as of now, too.

**Comment by TY1Fan** [comment]
> Could we add in the reason for why only 8 digit and 3,6,8,9 is accepted? Or are you going to resolve this in another commit. Also, It would be good to have a few test case to test this.
> 
> You need to cite what is not working as of now, too. image

Hi ive made the necessary changes.

**Comment by Feng1231** [comment]
You need to cite the PR that checks for valid phone number

**Comment by TY1Fan** [comment]
> You need to cite the PR that checks for valid phone number

Hi, ive added the past pr that is responsible for phone number validation

**Review by Feng1231 — APPROVED** [review]
Thanks for the changes

**Pull request merged**
