### PR TITLE
Update UG

### PR DESCRIPTION
**Pull request by teamotitan**
Previously, user guide did not include command summary for income, as well as image of output for income command

Let's
*include income in the command summary, as well as include images of output for income command

### CODE REVIEW

**Review by DennieDan — APPROVED** [review]
Can you help include the `exit` command in the Command Summary also, please?

**Review by TY1Fan — APPROVED** [review]
LGTM

**Comment by teamotitan** [comment]
> Can you help include the `exit` command in the Command Summary also, please?

Okay I will do that

**Review by TY1Fan — APPROVED** [review]
LGTM

**Pull request merged**
